SP_1:
  client_id: 500ca9b4-8e8f-465b-9039-4c9c150fa724
  client_name: SP-NAVEEN-UK-SUPPORT-DEVTEST
  client_secret: tEj8Q~C~h1~Nh6jNhyjPB0rI_6SnunaJiGtxSdqK
  tenant_id: 44bb2b85-300c-44d0-b08a-658ac3914f86
